[supervisord]
nodaemon=true
logfile=/var/www/html/supervisord.log
logfile_maxbytes=5MB

[program:apache2]
command=apache2-foreground
autostart=true
autorestart=true
stdout_logfile=/var/www/html/apache.log
stderr_logfile=/var/www/html/apache-error.log

[program:php-websocket]
command=php /var/www/html/server.php
autostart=true
autorestart=true
stdout_logfile=/var/www/html/server.log
stderr_logfile=/var/www/html/server-error.log
